### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by jpaulino04** [larandvit/ebcdic-parser#1]
Hello Saversky,

I am trying your application, however, when I run the script a cmd prompt pops up and closes right away. Can you provide any guidance on proper usage. The following is how I'm running the app:

>> .\ebcdic_parser.py --input file .\ebcdicfile.txt --outputfolder .\outputs\

Any requirements that I'am not satisfying?

Thanks

**Comment by jpaulino04** [comment]
Hey I made some progress:

python .\ebcdic_parser.py --inputfile .\ebcdic.txt --outputfolder .\outputs\test.txt --layoutfile .\layout-sample.json --verbose

Apparently the conversion runs without error but I don't see the output converted file.

Any suggestion?

**Comment by larandvit** [comment]
Hi @jpaulino04,
Can you send a screenshot of output after running your command?
Thanks.

**Comment by jpaulino04** [comment]
![sample output ebcdic_parser](https://user-images.githubusercontent.com/23201912/65250288-57524c80-dac3-11e9-9393-87ea34c39a2a.JPG)


Thank you for replaying. Also note I have JAVABRIDGEINCLUDED set to 'False'.

This is what i get (picture attached):

PS C:\Users\Jose\Desktop\dev-folders\ebcdic-parser> python .\ebcdic_parser.py --inputfile .\ebcdic.txt --outputfolder .\outputs\  --layoutfile .\layout-sample.json

Processing file... ebcdic.txt
Application version: 2.1.2
Stated: 2019-09-19 09:52:10.530067
Parameters:
-----------------------------------
Data folder: .
Output folder: .\outputs\
Layout file: .\layout-sample.json
Output delimiter: \t
Output file extension: .txt
Ignore conversion errors: no
Log file: .\ebcdic_parser.log
Python encoding:  yes
Encoding name: cp037
Group records:  no
Group records level 2:  no
Show information on screen: yes
Format: (1) Single schema
-----------------------------------
Processed data: ebcdic.txt
Completed: 2019-09-19 09:52:10.996069
PS C:\Users\Jose\Desktop\dev-folders\ebcdic-parser>

**Comment by larandvit** [comment]
@jpaulino04 
Log shows that it was not found any records in ebcdic.txt file. After "Processed data: ebcdic.txt" line, It should be stated how many rows processed. Can you share your layout file?

**Comment by jpaulino04** [comment]
@larandvit  thank you for pointing that out. I think that's the problem.

I am using a test ebcdic.txt file before using real files, and I'm  also using the sample layout exactly file as it is in your github repo.

Would need to match that file with the contents of the ebcdic file to be able to convert it?

Also, can the application convert multiple files at once?

Thank you for your time.

**Comment by larandvit** [comment]
@jpaulino04 
Layout files describe structure of EBCDIC ones. They must correspond each other. Layout is similar to COBOL copybook.
The tool can process one file in a time but you can create a shell script to run it in a loop for each file in a folder or folders.

**Comment by jpaulino04** [comment]
Great, thank you very much for your help and for the application!
