### ISSUE TITLE
Basic record filtering and delimiter cleaning from string value fields

### ISSUE THREAD

**Issue by vbdevpro** [larandvit/ebcdic-parser#11]
Add the ability to flunk records based on criteria in a given field by adding an optional "flunkif" element to the json layout field on a per field basis. Also adding the ability to optionally strip the delimiter character, carriage return and new line characters would be invaluable for large data engineering projects that feature string input without edit checks. Example for "flunkif" below: 

"name": "employee_type", "type": "string", "size": 1, "flunkif":"p,x,c"

**Comment by vbdevpro** [comment]
I've already added this functionality to my fork of your repository and would love to issue a pull request to contribute it upstream to this repository. I've also updated the documentation.

**Comment by vbdevpro** [comment]
Let me know if I should proceed. Thanks!

**Comment by larandvit** [comment]
Hi Chris,
Please open your pull request.
Thanks.
Vitaly

**Comment by vbdevpro** [comment]
Closing. Thank you!!!
