### ISSUE TITLE
Output file not getting created 

### ISSUE THREAD

**Issue by darkside0522** [larandvit/ebcdic-parser#3]
HI @larandvit ,

Appreciate all your effort in helping others in EBCDIC parser. I am finding it very helpful as well. However i did encounter an issue where it is not creating a output file but the process gets completed without any errors.
Initally i got this error 
python ebcdic_parser.py --inputfile "/Users/311_calls_for_service_requests_sample.dat" --outputfolder "/Users/output.csv" --layoutfile "/Users/311_calls_for_service_requests_all_strings.json" --outputdelimiter , --ignoreconversionerrors no --pythonencoding no --grouprecords no --verbose yes 

('Processing file...', '311_calls_for_service_requests_sample.dat')
('Application version:', '2.1.2')
('Stated:', datetime.datetime(2021, 1, 19, 16, 16, 21, 877796))
Parameters:
-----------------------------------
Data folder: /Users/311_calls_for_service_requests_all_strings
('Output folder:', '/Users/output.csv')
Layout file: /Users/layout_repository/311_calls_for_service_requests_all_strings.json
('Output delimiter:', ',')
Output file extension: .txt
('Ignore conversion errors:', 'no')
Log file: ebcdic_parser.log
('Python encoding: ', 'no')
Encoding name: cp037
('Group records: ', 'no')
('Group records level 2: ', 'no')
('Show information on screen:', 'yes')
Unexpected error: TypeError at line 496: category() argument 1 must be unicode, not str
('Number of bytes read:', 0)
('Completed:', datetime.datetime(2021, 1, 19, 16, 16, 21, 880120))

And i fixed this locally doing below 
488     def buildControlCharRegex(self):
489         # create a list of control (unreadable/invisible) characters
490         allChars = (unichr(i) for i in xrange(sys.maxunicode))
491         controlChars = ''.join(c for c in allChars if unicodedata.category(c)[0] == 'C')
492         return re.compile('[%s]' % re.escape(controlChars))

This time i got this output but output file did not get created. Can you please help me in helping me on this.

('Processing file...', '311_calls_for_service_requests_sample.dat')
('Application version:', '1')
('Stated:', datetime.datetime(2021, 1, 19, 16, 17, 13, 737330))
Parameters:
-----------------------------------
Data folder: /Users/311_calls_for_service_requests_all_strings
('Output folder:', '/Users/output.csv')
Layout file: /Users/layout_repository/311_calls_for_service_requests_all_strings.json
('Output delimiter:', ',')
Output file extension: .txt
('Ignore conversion errors:', 'no')
Log file: ebcdic_parser.log
('Python encoding: ', 'no')
Encoding name: cp037
('Group records: ', 'no')
('Group records level 2: ', 'no')
('Show information on screen:', 'yes')
('Format:', '(1)', 'Single schema')
-----------------------------------
Java encoding is not available as JAVABRIDGEINCLUDED=False
('Number of bytes read:', 0)
('Completed:', datetime.datetime(2021, 1, 19, 16, 17, 13, 786281))

**Comment by larandvit** [comment]
Hi @darkside0522 ,

Change `--pythonencoding no` setting to `--pythonencoding yes` to run the sample. If you need to use Java encodings, javabridge Python library has to be installed and `JAVABRIDGEINCLUDED=True` is adjusted in the code.
Thanks.
Vitaly.

**Comment by darkside0522** [comment]
@larandvit Thanks !! Was able to run  and generate the output file.

**Comment by darkside0522** [comment]
@larandvit is it possible to read the files from the google storage?

**Comment by larandvit** [comment]
Hi @darkside0522 
The tool doesn't support reading directly from the Google storage but it might be done mapping or mounting your Google storage to your OS file system.
Vitaly.

**Comment by darkside0522** [comment]
@larandvit i have a single file which has multiple segments in it in that case it possible to parse the data as per the segments ? Just to give you an example:
segment 1 schema :

column       from    to
uid                 1       3
name           4       10
age              11      14

segment.   2 schema :
column           from    to
uid                     1       3
last name          4       10
number             11      14

segment 3 schema :
column           from      to
uid                          1       3
middlename          4       10
age                        11      14

there may be a case where some segment might exist or not.

**Comment by larandvit** [comment]
Hi @darkside0522 
It seems your layout has a missing column. It should be the record type column to separate segments out. You can find a sample in https://github.com/larandvit/ebcdic-parser/issues/2.
Vitaly.

**Comment by darkside0522** [comment]
@larandvit to be exact below is my schema file looks like.
header record: 1000 bytes which consists of below columns
column name from_bytes to_bytes 
type                 1                    4
name                5                   11
age                   12                  15
filler                  16                 1000

detailed record  1000 bytes consists of below columns
column_name from_bytes to_bytes 
type                  1                    4
record id           5                   11
column2           12                  15
column3           16                 1000

detailed record 1 1000 bytes consists of below columns
column_name from_bytes to_bytes 
type                  1                    4
record id           5                   11
column2           12                  15
column3           16                 1000

Trailer record 1000 bytes consists of below columns
column name from_bytes to_bytes 
type                 1                    4
name                5                   11
age                   12                  15
filler                  16                 1000

**Comment by darkside0522** [comment]
@larandvit  to start  with i created this schema kindly ignore the bytes  and column names those are not accurate.
Should i have the keyfields for all the schemas?  just an example
because i have to parse it based on type. (ex: type = A , C , E) 
{
    "description": "sample",
    
    "header": [
        {
            "name": "header", "type": "skip", "size": 100
        }
    ],
    "footer": [
        {
            "name": "footer", "type": "skip", "size": 52
        }
    ],

    "keyfields": [
		{
			"keytype": "layouttype",
			"name": "A , C , E ",         /* this does not look accurate to me can you suggest ?*/ 
			"type": "string",
			"size": 1
		}
	],
    "layouts": [
        {
            "layouttype": "1",
            "layout": [
            
				{"name":"type","type": "string","size":1},
				{"name":"name","type": "string","size":3},
				{"name":"status_notes","type": "string","size":15},
				{"name":"service_name","type": "string","size":900
        },
        {
            	"layouttype": "2",
		"layout": [
            
				{"name":"type","type": "string","size":1},
				{"name":"name","type": "string","size":3},
				{"name":"status_notes","type": "string","size":15},
				{"name":"service_name","type": "string","size":900
			]
        },

        {
            	"layouttype": "3",
		"layout": [
            
				{"name":"type","type": "string","size":1},
				{"name":"name","type": "string","size":3},
				{"name":"status_notes","type": "string","size":15},
				{"name":"service_name","type": "string","size":900
			]
        }
    ]
}

**Comment by darkside0522** [comment]
@larandvit  it gave me this error , it identified multi schema though.
('Format:', '(2)', 'Multi-schema fixed length')
-----------------------------------
('Error in finding layout type in layout file: Layout type in input file -', '')

**Comment by larandvit** [comment]
Hi @darkside0522 
You need to make changes

1. Place column name here `"name": "A , C , E ",`, for example, `"name": "recordtype",`
2. What values do you expect for each segment type (record type)? Is it A, B, C? If so, replace
`"layouttype": "1",` with `"layouttype": "A",`
`"layouttype": "2",` with `"layouttype": "C",`
`"layouttype": "3",` with `"layouttype": "E",`
3. Remove `{"name":"type","type": "string","size":1},` from each segment. The column is defined in **keyfields** section. Your output will be a file for each segment
4. It seems a missing closing bracket for C and E segments
`{"name":"service_name","type": "string","size":900` -> `{"name":"service_name","type": "string","size":900}`

Vitaly.

**Comment by darkside0522** [comment]
@larandvit  Thanks for  the inputs. I did make these changes and when i am running i am getting below error. Looks like there are some special characters that codec is not able to handle.  did you come across this by any chance ? or how can we handle this ?

-----------------------------------
Conversation error	Layout type: main	status	u
                                                         	'ascii' codec can't encode character u'\xcd' in position 0: ordinal not in range(128)
('Number of bytes read:', 1879)
('Completed:', datetime.datetime(2021, 1, 25, 13, 26, 4, 399043))

**Comment by larandvit** [comment]
@darkside0522 
Can you provide the full information from your screen? Did you check what output was generated by thte tool? It should be some output because a portion of data was read.
I validate content of an input file with binary viewer/editor to make sure that the Cobol layout corresponds to an input file. 
Vitaly.

**Comment by darkside0522** [comment]
@larandvit 
('Processing file...', 'test.txt')
('Application version:', '1')
('Stated:', datetime.datetime(2021, 1, 25, 23, 2, 8, 109834))
Parameters:
-----------------------------------
Data folder: /Users/
('Output folder:', '/Users/')
Layout file: /Users/schema_yesheader_nofooter.json
('Output delimiter:', ',')
Output file extension: .csv
('Ignore conversion errors:', 'no')
Log file: ebcdic_parser.log
('Python encoding: ', 'yes')
Encoding name: cp037
('Group records: ', 'no')
('Group records level 2: ', 'no')
('Show information on screen:', 'yes')
('Format:', '(1)', 'Single schema')
-----------------------------------
Conversation error	Layout type: main	status	u
                                                         	'ascii' codec can't encode character u'\xcd' in position 0: ordinal not in range(128)
('Number of bytes read:', 1879)
('Completed:', datetime.datetime(2021, 1, 25, 23, 2, 8, 161886))

**Comment by larandvit** [comment]
@darkside0522 
You should have multi-schema format but it shows as single-schema. The tool doesn't recognize the layout json as multi-schema one.
Sizes in the layout file is not correct. For example,
type 1 4 - size: 4
name 5 11 - size: 7
age 12 15 - size: 4
filler 16 1000 - size: 985

So

"keyfields": [
	{
		"keytype": "layouttype",
		"name": "recordtype",  
		"type": "string",
		"size": 4
	}

 {
        "layouttype": "1",
        "layout": [
			{"name":"name","type": "string","size":7},
			{"name":"status_notes","type": "string","size":4},
			{"name":"service_name","type": "string","size":985
    },

Vitaly.

**Comment by larandvit** [comment]
@darkside0522 

I've looked fresh eyes at your data. You don't need multi-schema as there is the same number of columns and sizes for each record type. Single-schema should work if you define all your fields as strings and after transform your data into appropriate data types.  

You can go with multi-schema as well. It seems single-schema is beneficial for you because you might need to keep the original record order to group related records.

If you go with single schema.

1. Remove **keyfields** section
2. Keep only 1 layout. I guess you should have done it already.
```
{
"layouttype": "main",
"layout": [
{"name":"type","type": "string","size":4},
{"name":"name","type": "string","size":7},
{"name":"status_notes","type": "string","size":4},
{"name":"service_name","type": "string","size":985}
]
```
Vitaly.

**Comment by darkside0522** [comment]
@larandvit I am looking for a multi schema because i have a multiple segments in the file like (let me give you an example of ascii pattern) Columns in the layout might be same because its just an example.
( **A**000000012345600000000000000000000**C**100000000000000022222222MLTREDF0000**Z**00000000000000). in here my segments would be A,C,Z

I have this schema created 
{
    "description": "sample",
    
    "header": [
        {
            "name": "header", "type": "skip", "size": 100
        }
    ],
    "footer": [
        {
            "name": "footer", "type": "skip", "size": 52
        }
    ],

    "keyfields": [
		{
			"keytype": "layouttype",
			"name": "recordtype",
			"type": "string",
			"size": 4
		}
	],
    "layouts": [
        {
            "layouttype": "A",
            "layout": [
            	{"name":"name","type": "string","size":7},
		{"name":"status_notes","type": "string","size":4},
		{"name":"service_name","type": "string","size":985}]
        },
        {
            "layouttype": "C",
            "layout": [
            
		{"name":"id","type": "string","size":7},
		{"name":"amount","type": "string","size":4},
		{"name":"phone_number","type": "string","size":985}]
        },
{
            "layouttype": "Z",
            "layout": [
            
		{"name":"age","type": "string","size":7},
		{"name":"ssn","type": "string","size":4},
		{"name":"filler","type": "string","size":985}]
        }
    ]
}


I am getting this error 
('Processing file...', 'test.txt')
('Application version:', '1')
('Stated:', datetime.datetime(2021, 1, 26, 10, 17, 3, 158654))
Parameters:
-----------------------------------
Data folder: /Users/
('Output folder:', '/Users/')
Layout file: /Users/multi_schema_test.json
('Output delimiter:', ',')
Output file extension: .csv
('Ignore conversion errors:', 'no')
Log file: ebcdic_parser.log
('Python encoding: ', 'yes')
Encoding name: cp037
('Group records: ', 'no')
('Group records level 2: ', 'no')
('Show information on screen:', 'yes')
('Format:', '(2)', 'Multi-schema fixed length')
-----------------------------------
('Error in finding layout type in layout file: Layout type in input file -', '')
('Number of bytes read:', 104)
('Completed:', datetime.datetime(2021, 1, 26, 10, 17, 3, 218853))

**Comment by larandvit** [comment]
@darkside0522 

A question. Why do you skip 100 bytes from the top of the file? Do you have any "garbage" which is not data?
```
"header": [
    {
        "name": "header", "type": "skip", "size": 100
    }
```

The error message means that it was extracted **recordtype** from the initial file and the value is not as expected: `('Error in finding layout type in layout file: Layout type in input file -', '')`. The value list is "A", "C", "Z". It was skipped 100 bytes, and the next column has to be 4 bytes record type: `('Number of bytes read:', 104)`.

Also, it might be a potential issue that the record type is 1 byte character (A or C or Z) but it defined as 4 byte column. It will be extracted 4 bytes and it will be compared to the segment (record type) values. Do you know what is actually sitting in 4 bytes?

Vitaly.

**Comment by darkside0522** [comment]
@larandvit i have defined length of header and trailer record which i don't want it to be considered... 
by any chance do you have 10-15min we could connect and i can show you how my schema looks like ?

**Comment by larandvit** [comment]
@darkside0522 
I'm busy now. If we could do it between 9:00pm - 10:30pm EST.

**Comment by larandvit** [comment]
@darkside0522 
**header** and **footer** sections are applied to entire file. They are not applied to segment level.

**Comment by darkside0522** [comment]
@larandvit i am available between 9pm - 10:30pm est. Let me know how to connect

**Comment by larandvit** [comment]
@darkside0522 
You are a presenter. You can pick up a tool and send a link. I have Skype.

**Comment by darkside0522** [comment]
@larandvit can you check if you are able to join this meet
https://meet.google.com/ist-kcox-qrz?authuser=0

**Comment by darkside0522** [comment]
@larandvit you got disconnected...

**Comment by larandvit** [comment]
@darkside0522 
I'm back online. My internet last week is pretty bad.

**Comment by darkside0522** [comment]
@larandvit let me know if you have some time today to sync up... i just have a few columns in schema and few bytes of record in the file. still i am getting error.

**Comment by larandvit** [comment]
@darkside0522 
Sure. I'm available between 9:00pm:10:30pm EST. I can use the same meeting link as before.

**Comment by darkside0522** [comment]
@larandvit i am on the meet if you have some time.

**Comment by larandvit** [comment]
@darkside0522 
I've developed the debug mode. You can try it. The option is `--debug yes`. I've tested it only with single schema.
Vitaly.

**Comment by darkside0522** [comment]
@larandvit thanks this is helpful. By any chance do you happen to work on parsing fixed width file with multi segments ??

**Comment by larandvit** [comment]
@darkside0522 
I worked on different types of EBCDIC files including fixed length with multiple segments.

**Comment by larandvit** [comment]
@darkside0522 
I've added a new sample to the repository. It's multi-schema fixed record length which is the same type as you have. The sample includes COBOL layout, translated conversion rules json file, data file, and run command. Please check README and .\test_data\ola013k folder.
