### ISSUE TITLE
No able to space as layouttype

### ISSUE THREAD

**Issue by PratyushPriyamKuanr** [larandvit/ebcdic-parser#4]
@larandvit Thank you very much for your code. It helped me a lot to convert some files from ebcidic to ASCII. There was issue in conversion of those files for which I mentioned layouttype as space(" "). Am I doing anything wrong

**Comment by larandvit** [comment]
Hi @PratyushPriyamKuanr 
If you could provide a sample of your layout and data?
Thanks.

**Comment by PratyushPriyamKuanr** [comment]
> Hi @PratyushPriyamKuanr If you could provide a sample of your layout and data? Thanks.

Sorry but it is not possible to provide the file . Will it be okay if I share the copy book and the json created. Sorry for the trouble

**Comment by larandvit** [comment]
@PratyushPriyamKuanr 
I know that the data might be sensitive. I didn't mean your original file, just a sample reflecting your data. The json files with the copy book should be fine now.
Thanks.
