### ISSUE TITLE
Problem parsing multi-schema fixed length sample ola013k

### ISSUE THREAD

**Issue by gl-tlo** [larandvit/ebcdic-parser#5]
Thanks for the great work first. I have tried to run the multi-schema fixed-length sample ola013k using the following parameters:

--inputfile
"./test_data/ola013k/olf001l.ebc"
--outputfolder
"./test_data/ola013k/output"
--layoutfile
"./layout_repository/ola013k_rules.json"
--logfolder
"./test_data/ola013k/log"

However, when edcdic_parser.py gets to line 746, keyField.rawValue is not set and causes an issue. It seems like keyField.rawValue is only set when layoutDefinition.isVariableFields is True. I am wondering if you can check if I misconfigured the parameters. Thanks.

seems like changing line 746 from

if (layoutDefinition.isVariableFields):

to 

if len(layoutDefinition.keyFields) > 0:

got it going and able to generate multiple files. but not sure if there are any other implications.

**Comment by larandvit** [comment]
Hello @gl-tlo,

I've added a new type of the layout recently and it broke the existing types. I need to figure out how to fix it to cover all 4 layout types. Meanwhile, if you need to convert types 1-3, you can use previous version of the tool (2.3.0) which can be extracted from the history of ebcdic_parser.py file. Sorry for inconvenience.
Thanks. 
Vitaly

**Comment by gl-tlo** [comment]
Great thanks. Will try the 2.3.0

**Comment by gl-tlo** [comment]
2.3.0 works

**Comment by larandvit** [comment]
I appreciate, @gl-tlo, your feedback.
