### ISSUE TITLE
Generate headers and include Keyfield data

### ISSUE THREAD

**Issue by gl-tlo** [larandvit/ebcdic-parser#6]
Hi got a second question. The output doesn't seem to include the headers using the name of the field and doesn't seem to include the keyfield data. Is there a way to include them in the output? Much appreciated.

**Comment by larandvit** [comment]
Hello,

The keyfield data and headers are not included in output. The keyfield data doesn't bring too much value and in some case, it is impossible to have it, for example, layout type, as it will be created separate files for each layout.  The headers can be added when output files are being imported to a database.

**Comment by gl-tlo** [comment]
great thanks.
