### ISSUE TITLE
Add to PyPI?

### ISSUE THREAD

**Issue by millsks** [larandvit/ebcdic-parser#7]
Would you be open to adding the ebcdic-parser to the PyPI?  We wanted to also get it added to conda-forge too.

**Comment by larandvit** [comment]
Hello,
Sure, I can add to PyPI. I need some time to learn conda-forge.
Thanks.

**Comment by millsks** [comment]
Great.  We appreciate it!

Once you get it on PyPI take a look at the grayskull package.  It helps you to set up a recipe to add to the staged recipes area. The link below will help walk you through step by step.

https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by larandvit** [comment]
Hello,
I've added ebcdic_parser to the PyPi. I'm still working on the documentation and adding code to the GitHub repository.
If you want to use it now, please do it.

Installation
`pip install ebcdic_parser`

Usage with a sample included in the GitHub repository

Import
`from ebcdic_parser.convert import run`

`run(r"<your location>\ebcdic-parser\tests\test_data\311_calls_for_service_requests_all_strings\311_calls_for_service_requests_sample.dat", 
    r"<your folder for an output file>",
    r"<your location>\ebcdic-parser\tests\layout_repository\311_calls_for_service_requests_all_strings.json",
    outputDelimiter=',')`

`run` function all parameters

`run(inputFile, outputFolder, layoutFile, logfolder, pythonEncoding, encodingName, outputDelimiter, outputFileExtension, ignoreConversionErrors, groupRecords, groupRecordsLevel2, verbose, debug)`

Thanks.

**Comment by DeflateAwning** [comment]
It would be great if you added the `pip install ebcdic_parser` command to the README!

**Comment by millsks** [comment]
Thanks @larandvit!  Is there an ETA on when it might be available on conda-forge?

**Comment by rxm7706** [comment]
I can start on creating the conda-forge recipe and add ebcdic-parser 3.0.0 to conda-forge.

**Comment by larandvit** [comment]
The repository has been updated with Pip code. The documentation has been updated to reflect Pip usage.

**Comment by rxm7706** [comment]
https://anaconda.org/conda-forge/ebcdic-parser
conda version is now available - 
@larandvit @millsks , I can add you as maintainers to the feedstock - If you want to be maintainers.

**Comment by larandvit** [comment]
Thank you, @rxm7706, for adding it to conda-forge. I don't mind to be a maintainer for it.

I need to update the documentation on PyPI. The documentation was updated only on GitHub.

**Comment by rxm7706** [comment]
Done ! 

https://github.com/conda-forge/ebcdic-parser-feedstock/pull/4

FYI - automerge is turned on right now -- https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-bot-automerge

https://github.com/conda-forge/ebcdic-parser-feedstock/pull/2

**Comment by millsks** [comment]
Thanks everyone!
