### ISSUE TITLE
Feature Request: Add support for running this project like `python3 -m ebcdic_parser ...`

### ISSUE THREAD

**Issue by DeflateAwning** [larandvit/ebcdic-parser#8]
The way to add support for this is shown in this commit here on a similar Python tool library: https://github.com/chardet/chardet/commit/0e9b7bc20366163efcc221281201baff4100fe19

This is useful for those who install this package with `pip`

**Comment by larandvit** [comment]
Pip implementation has been added to the repository. Please check the documentation (readme file).

**Comment by DeflateAwning** [comment]
I don't think you got what I was saying, sorry. This request isn't complete.

I want to be able to run this script like `python3 -m ebcdic_parser ...`. The way to do that is to add a `__main__.py` file, as in the linked commit when I opened the issue.

**Comment by larandvit** [comment]
Hi @DeflateAwning 
I've been working on your request. Another option to run as `python3 -m` is `python3 -m ebcdic_parser.convert`. If it works for you?

**Comment by DeflateAwning** [comment]
That would work, but generally it's preferable for the main one without a submodule to work instead of needing to name the submodule also

**Comment by larandvit** [comment]
Hi @DeflateAwning 
The requested feature has been developed.
Thanks.

**Comment by DeflateAwning** [comment]
Good stuff, great and easy improvement, Don't forget to mention it in the readme
